name: "Podcast Generator"
author: "Ray williams"
description: "Generate a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"

inputs:
  emails:
    description: The comiter's email address
    required: true
    default: ${{github.actor}}@localhost
  name: 
    description: The comitter's name
    required: true
    default: ${{github.actor}}
  